name: imswitch-uv-test

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Linux system deps (Xvfb/X11)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 \
            libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
        shell: bash

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install test deps with uv
        run: |
          # Prefer dev requirements if present
          if [ -f requirements-dev.txt ]; then
            uv pip install --system -r requirements-dev.txt
          else
            uv pip install --system pytest
          fi
          # Install additional test dependencies that might be needed
          uv pip install --system pytest-qt pytest-xvfb
        shell: bash

      - name: Install project with uv (editable)
        run: |
          echo "Installing project with UV..."
          uv pip install --system -e .
          echo "Checking if psygnal is installed..."
          uv pip list | grep psygnal || echo "psygnal not found"
          echo "Uninstalling psygnal..."
          uv pip uninstall psygnal || echo "psygnal uninstall failed (not installed)"
          echo "Installing psygnal from source..."
          uv pip install --system psygnal --no-binary :all:
          echo "Verifying installation..."
          python -c "import dataclasses_json; print('dataclasses_json imported successfully')" || echo "dataclasses_json import failed"
          python -c "import psygnal; print('psygnal imported successfully')" || echo "psygnal import failed"
        shell: bash

      - name: Verify installation
        run: |
          echo "=== UV pip list ==="
          uv pip list
          echo "=== Python package verification ==="
          python -c "import imswitch; print(f'ImSwitch version: {imswitch.__version__}')"
          echo "=== Testing critical imports ==="
          python -c "from imswitch.imcontrol.model import Options; print('Options import successful')" || echo "Options import failed"
        shell: bash

      - name: Run tests
        run: |
          if [ "$RUNNER_OS" = "Linux" ]; then
            xvfb-run --server-args "-screen 0 1920x1080x24" python -m pytest --pyargs imswitch/imcontrol/_test -v -s
          elif [ "$RUNNER_OS" = "Windows" ]; then
            # Keep Windows special-casing similar to existing workflow
            python -m pytest --pyargs imswitch/imcontrol/_test -v -s
          else
            # macOS: split API and unit to avoid sporadic issues
            python -m pytest imswitch/imcontrol/_test/api -v -s
            python -m pytest imswitch/imcontrol/_test/unit -v -s
          fi
        shell: bash
