name: imswitch-docker
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: openuc2-imswitch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0
        with:
          fetch-depth: 2
      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }}

      - name: Build and push Docker image (latest tag)
        uses: docker/build-push-action@v5.0.0
        with:
          context: docker
          file: docker/dockerfileImSwitchAMDNoQT
          push: true
          tags: ghcr.io/openuc2/imswitch-docker-amd64-noqt:latest
          labels: ${{ steps.meta.outputs.labels }}
          
